name: cursor_test_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  uuid: ^4.3.3
  get_it: ^7.7.0
  shared_preferences: ^2.2.2
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  mockito: ^5.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/logo.svg
    - assets/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"

flutter_native_splash:
  color: "#2196F3"
  image: assets/logo.png
  android: true
  ios: true
  web: true

scripts:
  format: flutter format .
  analyze: flutter analyze
  fix: flutter fix --apply
  test: flutter test
  clean: flutter clean